# fly.toml app configuration file generated for basic-memory on 2025-06-10T20:27:31-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'basic-memory'
primary_region = 'dfw'

[build]

[env]
  BASIC_MEMORY_DEFAULT_PROJECT = 'main'
  BASIC_MEMORY_PROJECTS = '{"main": "/app/data"}'
  FASTMCP_AUTH_ENABLED = 'false'
  FASTMCP_AUTH_PROVIDER = 'basic'
  FASTMCP_AUTH_ISSUER_URL = 'https://basic-memory.fly.dev'
  LOG_LEVEL = 'INFO'

[[mounts]]
  source = 'basic_memory_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/mcp'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
